//! Wire-format constants: magic, version, rank limit, opcodes and the stable
//! `DType` tag table.

use scirust_compute::DType;

/// Domain-separation prefix at the start of every Reference-format stream.
pub const REFERENCE_MAGIC: &[u8; 25] = b"SCIRUST-REFERENCE-KERNEL\0";

/// Largest rank a Reference-format layout may declare.
pub const REFERENCE_MAX_RANK: u16 = 32;

/// Attribute-tag constants (`u16`), stable once published.
pub(crate) const ATTRIBUTE_TAG_NONE: u16 = 0x0000;
pub(crate) const ATTRIBUTE_TAG_SCALE: u16 = 0x0001;
pub(crate) const ATTRIBUTE_TAG_PERMUTE: u16 = 0x0002;

/// Version of the Reference wire format.
///
/// # Versioning policy
///
/// * An incompatible structural change is a new **major** version.
/// * An explicitly supported extension is a new **minor** version.
///
/// Version 1.1 extends 1.0 only with new no-attribute opcodes. The decoder
/// accepts both 1.0 and 1.1 and rejects every other minor explicitly.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReferenceFormatVersion {
    major: u16,
    minor: u16,
}

impl ReferenceFormatVersion {
    pub const fn new(major: u16, minor: u16) -> Self {
        Self { major, minor }
    }

    pub const fn major(self) -> u16 {
        self.major
    }

    pub const fn minor(self) -> u16 {
        self.minor
    }
}

/// Latest Reference format version generated by this crate.
pub const REFERENCE_FORMAT_VERSION: ReferenceFormatVersion = ReferenceFormatVersion::new(1, 1);

/// Closed set of operations understood by Reference format v1.1.
///
/// Opcode values are published and never reassigned. The v1.0 values remain
/// bit-for-bit stable; v1.1 only appends new values.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum ReferenceOpcode {
    Relu,
    Exp,
    Log,
    Scale,
    ReluGrad,
    ZerosLike,
    OnesLike,
    Add,
    Sub,
    Mul,
    Div,
    ShapeCopy,
    BroadcastTo,
    ReduceSumTo,
    Permute,
    MatMul,
    BatchMatMul,
}

impl ReferenceOpcode {
    /// Stable wire value. Never reassigned to a different operation.
    pub const fn code(self) -> u16 {
        match self {
            Self::Relu => 0x0001,
            Self::Exp => 0x0002,
            Self::Log => 0x0003,
            Self::Scale => 0x0004,
            Self::ReluGrad => 0x0005,
            Self::ZerosLike => 0x0006,
            Self::OnesLike => 0x0007,
            Self::Add => 0x0010,
            Self::Sub => 0x0011,
            Self::Mul => 0x0012,
            Self::Div => 0x0013,
            Self::ShapeCopy => 0x0020,
            Self::BroadcastTo => 0x0021,
            Self::ReduceSumTo => 0x0022,
            Self::Permute => 0x0030,
            Self::MatMul => 0x0040,
            Self::BatchMatMul => 0x0041,
        }
    }

    /// Recovers the opcode named by a wire value, or `None` if unknown.
    pub const fn from_code(code: u16) -> Option<Self> {
        match code {
            0x0001 => Some(Self::Relu),
            0x0002 => Some(Self::Exp),
            0x0003 => Some(Self::Log),
            0x0004 => Some(Self::Scale),
            0x0005 => Some(Self::ReluGrad),
            0x0006 => Some(Self::ZerosLike),
            0x0007 => Some(Self::OnesLike),
            0x0010 => Some(Self::Add),
            0x0011 => Some(Self::Sub),
            0x0012 => Some(Self::Mul),
            0x0013 => Some(Self::Div),
            0x0020 => Some(Self::ShapeCopy),
            0x0021 => Some(Self::BroadcastTo),
            0x0022 => Some(Self::ReduceSumTo),
            0x0030 => Some(Self::Permute),
            0x0040 => Some(Self::MatMul),
            0x0041 => Some(Self::BatchMatMul),
            _ => None,
        }
    }

    /// Fixed operand arity of this opcode.
    pub const fn operand_count(self) -> u16 {
        match self {
            Self::Add
            | Self::Sub
            | Self::Mul
            | Self::Div
            | Self::ReluGrad
            | Self::MatMul
            | Self::BatchMatMul => 2,
            Self::Relu
            | Self::Exp
            | Self::Log
            | Self::Scale
            | Self::ZerosLike
            | Self::OnesLike
            | Self::ShapeCopy
            | Self::BroadcastTo
            | Self::ReduceSumTo
            | Self::Permute => 1,
        }
    }

    /// Minimum Reference minor version in which this opcode is valid.
    pub const fn minimum_minor(self) -> u16 {
        match self {
            Self::ReluGrad
            | Self::ZerosLike
            | Self::OnesLike
            | Self::BroadcastTo
            | Self::ReduceSumTo
            | Self::MatMul
            | Self::BatchMatMul => 1,
            _ => 0,
        }
    }
}

/// Maps a `DType` to its stable wire tag.
pub(crate) const fn dtype_to_tag(dtype: DType) -> u16 {
    match dtype {
        DType::Bool => 0x0001,
        DType::U8 => 0x0002,
        DType::I8 => 0x0003,
        DType::U16 => 0x0004,
        DType::I16 => 0x0005,
        DType::F16 => 0x0006,
        DType::Bf16 => 0x0007,
        DType::U32 => 0x0008,
        DType::I32 => 0x0009,
        DType::F32 => 0x000A,
        DType::U64 => 0x000B,
        DType::I64 => 0x000C,
        DType::F64 => 0x000D,
        _ => 0x0000,
    }
}

/// Recovers the `DType` named by a wire tag.
pub(crate) const fn dtype_from_tag(tag: u16) -> Option<DType> {
    match tag {
        0x0001 => Some(DType::Bool),
        0x0002 => Some(DType::U8),
        0x0003 => Some(DType::I8),
        0x0004 => Some(DType::U16),
        0x0005 => Some(DType::I16),
        0x0006 => Some(DType::F16),
        0x0007 => Some(DType::Bf16),
        0x0008 => Some(DType::U32),
        0x0009 => Some(DType::I32),
        0x000A => Some(DType::F32),
        0x000B => Some(DType::U64),
        0x000C => Some(DType::I64),
        0x000D => Some(DType::F64),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn all_opcodes() -> [ReferenceOpcode; 17] {
        [
            ReferenceOpcode::Relu,
            ReferenceOpcode::Exp,
            ReferenceOpcode::Log,
            ReferenceOpcode::Scale,
            ReferenceOpcode::ReluGrad,
            ReferenceOpcode::ZerosLike,
            ReferenceOpcode::OnesLike,
            ReferenceOpcode::Add,
            ReferenceOpcode::Sub,
            ReferenceOpcode::Mul,
            ReferenceOpcode::Div,
            ReferenceOpcode::ShapeCopy,
            ReferenceOpcode::BroadcastTo,
            ReferenceOpcode::ReduceSumTo,
            ReferenceOpcode::Permute,
            ReferenceOpcode::MatMul,
            ReferenceOpcode::BatchMatMul,
        ]
    }

    #[test]
    fn opcode_round_trips_through_its_code() {
        for opcode in all_opcodes() {
            assert_eq!(ReferenceOpcode::from_code(opcode.code()), Some(opcode));
        }
    }

    #[test]
    fn opcode_values_are_stable_and_distinct() {
        let codes = all_opcodes().map(ReferenceOpcode::code);
        assert_eq!(
            codes,
            [
                0x0001, 0x0002, 0x0003, 0x0004, 0x0005, 0x0006, 0x0007, 0x0010, 0x0011,
                0x0012, 0x0013, 0x0020, 0x0021, 0x0022, 0x0030, 0x0040, 0x0041,
            ]
        );
    }

    #[test]
    fn v1_1_only_opcodes_are_version_marked() {
        for opcode in all_opcodes() {
            let expected = if matches!(
                opcode,
                ReferenceOpcode::ReluGrad
                    | ReferenceOpcode::ZerosLike
                    | ReferenceOpcode::OnesLike
                    | ReferenceOpcode::BroadcastTo
                    | ReferenceOpcode::ReduceSumTo
                    | ReferenceOpcode::MatMul
                    | ReferenceOpcode::BatchMatMul
            ) {
                1
            } else {
                0
            };
            assert_eq!(opcode.minimum_minor(), expected);
        }
    }

    #[test]
    fn unknown_opcode_is_rejected() {
        assert_eq!(ReferenceOpcode::from_code(0xFFFF), None);
    }

    #[test]
    fn every_known_dtype_round_trips_through_its_tag() {
        for dtype in [
            DType::Bool,
            DType::U8,
            DType::I8,
            DType::U16,
            DType::I16,
            DType::F16,
            DType::Bf16,
            DType::U32,
            DType::I32,
            DType::F32,
            DType::U64,
            DType::I64,
            DType::F64,
        ] {
            assert_eq!(dtype_from_tag(dtype_to_tag(dtype)), Some(dtype));
        }
    }

    #[test]
    fn tag_zero_is_reserved_and_unknown() {
        assert_eq!(dtype_from_tag(0x0000), None);
    }

    #[test]
    fn unknown_and_known_unsupported_dtype_tags_remain_distinct() {
        assert_eq!(dtype_from_tag(0xBEEF), None);
        assert_eq!(dtype_from_tag(0x0001), Some(DType::Bool));
    }
}
