use alloc::{format, string::String, vec, vec::Vec};
use core::fmt;

use scirust_compute::{DType, Shape};

use crate::{Graph, GraphError, NodeId, Operation, TensorType};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AutodiffError {
    InvalidGraph(GraphError),
    InvalidNode(NodeId),
    NonFloatingPoint { node: NodeId, dtype: DType },
    UnsupportedOperation { node: NodeId, operation: Operation },
    MatMulRequiresRank2 { node: NodeId },
}

impl fmt::Display for AutodiffError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidGraph(error) => write!(f, "invalid graph during autodiff: {error}"),
            Self::InvalidNode(node) => write!(f, "autodiff references unknown node {}", node.get()),
            Self::NonFloatingPoint { node, dtype } => write!(
                f,
                "autodiff node {} has non-floating dtype {dtype:?}",
                node.get()
            ),
            Self::UnsupportedOperation { node, operation } => write!(
                f,
                "autodiff does not define a rule for node {} operation {operation:?}",
                node.get()
            ),
            Self::MatMulRequiresRank2 { node } => write!(
                f,
                "autodiff currently requires rank-2 MatMul at node {}",
                node.get()
            ),
        }
    }
}

impl std::error::Error for AutodiffError {}

impl From<GraphError> for AutodiffError {
    fn from(value: GraphError) -> Self {
        Self::InvalidGraph(value)
    }
}

/// Result of reverse-mode transformation with an explicit cotangent input.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VjpGraph {
    pub graph: Graph,
    pub primal_output: NodeId,
    pub cotangent_input: NodeId,
    pub gradients: Vec<NodeId>,
}

/// Result of scalar/tensor `grad`: the seed is generated by `OnesLike`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GradGraph {
    pub graph: Graph,
    pub primal_output: NodeId,
    pub gradients: Vec<NodeId>,
}

/// Result of forward-mode transformation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct JvpGraph {
    pub graph: Graph,
    pub primal_output: NodeId,
    pub tangent_output: NodeId,
    pub tangent_inputs: Vec<NodeId>,
}

/// Reverse-mode vector-Jacobian product.
///
/// The transformed graph has one extra input named `__scirust_cotangent` with
/// the same type as `output`; transformed outputs are gradients in `wrt` order.
pub fn vjp(source: &Graph, output: NodeId, wrt: &[NodeId]) -> Result<VjpGraph, AutodiffError> {
    source.validate()?;
    ensure_floating(source, output)?;
    for &node in wrt {
        ensure_floating(source, node)?;
    }

    let (mut graph, primal) = copy_primal(source)?;
    let primal_output = mapped(&primal, output)?;
    let output_type = node_type(source, output)?.clone();
    let cotangent_input = graph.add_input("__scirust_cotangent", output_type)?;

    let gradients = reverse_accumulate(source, &mut graph, &primal, output, cotangent_input, wrt)?;
    graph.set_outputs(gradients.clone())?;

    Ok(VjpGraph {
        graph,
        primal_output,
        cotangent_input,
        gradients,
    })
}

/// Reverse-mode gradient using an in-graph all-one seed.
///
/// For non-scalar outputs this computes the gradient of the sum of output
/// elements, equivalent to a VJP with an all-one cotangent.
pub fn grad(source: &Graph, output: NodeId, wrt: &[NodeId]) -> Result<GradGraph, AutodiffError> {
    source.validate()?;
    ensure_floating(source, output)?;
    for &node in wrt {
        ensure_floating(source, node)?;
    }

    let (mut graph, primal) = copy_primal(source)?;
    let primal_output = mapped(&primal, output)?;
    let seed = graph.add_node(
        Operation::OnesLike,
        vec![primal_output],
        node_type(source, output)?.clone(),
    )?;
    let gradients = reverse_accumulate(source, &mut graph, &primal, output, seed, wrt)?;
    graph.set_outputs(gradients.clone())?;

    Ok(GradGraph {
        graph,
        primal_output,
        gradients,
    })
}

/// Return a graph whose outputs are the primal value followed by its gradients.
pub fn value_and_grad(
    source: &Graph,
    output: NodeId,
    wrt: &[NodeId],
) -> Result<GradGraph, AutodiffError> {
    let mut transformed = grad(source, output, wrt)?;
    let mut outputs = Vec::with_capacity(1 + transformed.gradients.len());
    outputs.push(transformed.primal_output);
    outputs.extend(transformed.gradients.iter().copied());
    transformed.graph.set_outputs(outputs)?;
    Ok(transformed)
}

/// Forward-mode Jacobian-vector product.
///
/// One tangent input is added for every node in `wrt`, in the same order. The
/// transformed outputs are `[primal_output, tangent_output]`.
pub fn jvp(source: &Graph, output: NodeId, wrt: &[NodeId]) -> Result<JvpGraph, AutodiffError> {
    source.validate()?;
    ensure_floating(source, output)?;
    for &node in wrt {
        ensure_floating(source, node)?;
    }

    let (mut graph, primal) = copy_primal(source)?;
    let mut tangents = vec![None; source.nodes().len()];
    let mut tangent_inputs = Vec::with_capacity(wrt.len());

    for &node in wrt {
        let ty = node_type(source, node)?.clone();
        let tangent = graph.add_input(format!("__scirust_tangent_{}", node.get()), ty)?;
        tangents[node.get() as usize] = Some(tangent);
        tangent_inputs.push(tangent);
    }

    for (index, node) in source.nodes().iter().enumerate() {
        if tangents[index].is_some() {
            continue;
        }
        let id = NodeId::new(index as u32);
        let tangent = forward_rule(source, &mut graph, &primal, &tangents, id, node)?;
        tangents[index] = tangent;
    }

    let primal_output = mapped(&primal, output)?;
    let tangent_output = match tangents[output.get() as usize] {
        Some(id) => id,
        None => graph.add_node(
            Operation::ZerosLike,
            vec![primal_output],
            node_type(source, output)?.clone(),
        )?,
    };
    graph.set_outputs(vec![primal_output, tangent_output])?;

    Ok(JvpGraph {
        graph,
        primal_output,
        tangent_output,
        tangent_inputs,
    })
}

fn reverse_accumulate(
    source: &Graph,
    graph: &mut Graph,
    primal: &[NodeId],
    output: NodeId,
    seed: NodeId,
    wrt: &[NodeId],
) -> Result<Vec<NodeId>, AutodiffError> {
    let mut adjoints = vec![None; source.nodes().len()];
    adjoints[output.get() as usize] = Some(seed);

    for index in (0..source.nodes().len()).rev() {
        let Some(cotangent) = adjoints[index] else {
            continue;
        };
        let id = NodeId::new(index as u32);
        let node = &source.nodes()[index];
        reverse_rule(source, graph, primal, &mut adjoints, id, node, cotangent)?;
    }

    let mut gradients = Vec::with_capacity(wrt.len());
    for &node in wrt {
        let gradient = match adjoints[node.get() as usize] {
            Some(id) => id,
            None => graph.add_node(
                Operation::ZerosLike,
                vec![mapped(primal, node)?],
                node_type(source, node)?.clone(),
            )?,
        };
        gradients.push(gradient);
    }
    Ok(gradients)
}

fn reverse_rule(
    source: &Graph,
    graph: &mut Graph,
    primal: &[NodeId],
    adjoints: &mut [Option<NodeId>],
    id: NodeId,
    node: &crate::Node,
    cotangent: NodeId,
) -> Result<(), AutodiffError> {
    let p = |node_id| mapped(primal, node_id);
    let ty = |node_id| node_type(source, node_id).cloned();

    match &node.operation {
        Operation::Input { .. } | Operation::Constant { .. } => {}
        Operation::Add => {
            accumulate(graph, adjoints, node.inputs[0], cotangent, ty(node.inputs[0])?)?;
            accumulate(graph, adjoints, node.inputs[1], cotangent, ty(node.inputs[1])?)?;
        }
        Operation::Sub => {
            accumulate(graph, adjoints, node.inputs[0], cotangent, ty(node.inputs[0])?)?;
            let neg = graph.add_node(
                Operation::Scale { factor: crate::Scalar::f32(-1.0) },
                vec![cotangent],
                ty(node.inputs[1])?,
            )?;
            accumulate(graph, adjoints, node.inputs[1], neg, ty(node.inputs[1])?)?;
        }
        Operation::Mul => {
            let left = graph.add_node(
                Operation::Mul,
                vec![cotangent, p(node.inputs[1])?],
                ty(node.inputs[0])?,
            )?;
            let right = graph.add_node(
                Operation::Mul,
                vec![cotangent, p(node.inputs[0])?],
                ty(node.inputs[1])?,
            )?;
            accumulate(graph, adjoints, node.inputs[0], left, ty(node.inputs[0])?)?;
            accumulate(graph, adjoints, node.inputs[1], right, ty(node.inputs[1])?)?;
        }
        Operation::Div => {
            let left = graph.add_node(
                Operation::Div,
                vec![cotangent, p(node.inputs[1])?],
                ty(node.inputs[0])?,
            )?;
            let denominator = graph.add_node(
                Operation::Mul,
                vec![p(node.inputs[1])?, p(node.inputs[1])?],
                ty(node.inputs[1])?,
            )?;
            let numerator = graph.add_node(
                Operation::Mul,
                vec![cotangent, p(node.inputs[0])?],
                ty(node.inputs[1])?,
            )?;
            let quotient = graph.add_node(
                Operation::Div,
                vec![numerator, denominator],
                ty(node.inputs[1])?,
            )?;
            let right = graph.add_node(
                Operation::Scale { factor: crate::Scalar::f32(-1.0) },
                vec![quotient],
                ty(node.inputs[1])?,
            )?;
            accumulate(graph, adjoints, node.inputs[0], left, ty(node.inputs[0])?)?;
            accumulate(graph, adjoints, node.inputs[1], right, ty(node.inputs[1])?)?;
        }
        Operation::Scale { factor } => {
            let contribution = graph.add_node(
                Operation::Scale { factor: *factor },
                vec![cotangent],
                ty(node.inputs[0])?,
            )?;
            accumulate(graph, adjoints, node.inputs[0], contribution, ty(node.inputs[0])?)?;
        }
        Operation::Relu => {
            let contribution = graph.add_node(
                Operation::ReluGrad,
                vec![p(node.inputs[0])?, cotangent],
                ty(node.inputs[0])?,
            )?;
            accumulate(graph, adjoints, node.inputs[0], contribution, ty(node.inputs[0])?)?;
        }
        Operation::Exp => {
            let contribution = graph.add_node(
                Operation::Mul,
                vec![cotangent, p(id)?],
                ty(node.inputs[0])?,
            )?;
            accumulate(graph, adjoints, node.inputs[0], contribution, ty(node.inputs[0])?)?;
        }
        Operation::Log => {
            let contribution = graph.add_node(
                Operation::Div,
                vec![cotangent, p(node.inputs[0])?],
                ty(node.inputs[0])?,
            )?;
            accumulate(graph, adjoints, node.inputs[0], contribution, ty(node.inputs[0])?)?;
        }
        Operation::ReluGrad => {
            // d(mask(primal) * tangent)/d(tangent) = mask(primal). The
            // derivative of the discontinuous mask itself is defined as zero.
            let contribution = graph.add_node(
                Operation::ReluGrad,
                vec![p(node.inputs[0])?, cotangent],
                ty(node.inputs[1])?,
            )?;
            accumulate(graph, adjoints, node.inputs[1], contribution, ty(node.inputs[1])?)?;
        }
        Operation::ZerosLike | Operation::OnesLike | Operation::StopGradient => {}
        Operation::Checkpoint => {
            accumulate(graph, adjoints, node.inputs[0], cotangent, ty(node.inputs[0])?)?;
        }
        Operation::Reshape { .. } => {
            let contribution = graph.add_node(
                Operation::Reshape {
                    shape: ty(node.inputs[0])?.shape.clone(),
                },
                vec![cotangent],
                ty(node.inputs[0])?,
            )?;
            accumulate(graph, adjoints, node.inputs[0], contribution, ty(node.inputs[0])?)?;
        }
        Operation::Transpose { permutation } => {
            let inverse = inverse_permutation(permutation)
                .ok_or_else(|| AutodiffError::UnsupportedOperation {
                    node: id,
                    operation: node.operation.clone(),
                })?;
            let contribution = graph.add_node(
                Operation::Transpose { permutation: inverse },
                vec![cotangent],
                ty(node.inputs[0])?,
            )?;
            accumulate(graph, adjoints, node.inputs[0], contribution, ty(node.inputs[0])?)?;
        }
        Operation::MatMul => {
            require_rank2(source, id, node.inputs[0], node.inputs[1])?;
            let lhs_t_type = transposed_matrix_type(ty(node.inputs[0])?);
            let rhs_t_type = transposed_matrix_type(ty(node.inputs[1])?);
            let rhs_t = graph.add_node(
                Operation::Transpose { permutation: vec![1, 0] },
                vec![p(node.inputs[1])?],
                rhs_t_type,
            )?;
            let lhs_grad = graph.add_node(
                Operation::MatMul,
                vec![cotangent, rhs_t],
                ty(node.inputs[0])?,
            )?;
            let lhs_t = graph.add_node(
                Operation::Transpose { permutation: vec![1, 0] },
                vec![p(node.inputs[0])?],
                lhs_t_type,
            )?;
            let rhs_grad = graph.add_node(
                Operation::MatMul,
                vec![lhs_t, cotangent],
                ty(node.inputs[1])?,
            )?;
            accumulate(graph, adjoints, node.inputs[0], lhs_grad, ty(node.inputs[0])?)?;
            accumulate(graph, adjoints, node.inputs[1], rhs_grad, ty(node.inputs[1])?)?;
        }
        operation => {
            return Err(AutodiffError::UnsupportedOperation {
                node: id,
                operation: operation.clone(),
            });
        }
    }
    Ok(())
}

fn forward_rule(
    source: &Graph,
    graph: &mut Graph,
    primal: &[NodeId],
    tangents: &[Option<NodeId>],
    id: NodeId,
    node: &crate::Node,
) -> Result<Option<NodeId>, AutodiffError> {
    let p = |node_id| mapped(primal, node_id);
    let t = |node_id: NodeId| tangents[node_id.get() as usize];
    let ty = |node_id| node_type(source, node_id).cloned();

    let result = match &node.operation {
        Operation::Input { .. } | Operation::Constant { .. } => None,
        Operation::Add => add_optional(graph, t(node.inputs[0]), t(node.inputs[1]), node.output.clone())?,
        Operation::Sub => {
            let right = match t(node.inputs[1]) {
                Some(value) => Some(graph.add_node(
                    Operation::Scale { factor: crate::Scalar::f32(-1.0) },
                    vec![value],
                    node.output.clone(),
                )?),
                None => None,
            };
            add_optional(graph, t(node.inputs[0]), right, node.output.clone())?
        }
        Operation::Mul => {
            let left = match t(node.inputs[0]) {
                Some(value) => Some(graph.add_node(
                    Operation::Mul,
                    vec![value, p(node.inputs[1])?],
                    node.output.clone(),
                )?),
                None => None,
            };
            let right = match t(node.inputs[1]) {
                Some(value) => Some(graph.add_node(
                    Operation::Mul,
                    vec![p(node.inputs[0])?, value],
                    node.output.clone(),
                )?),
                None => None,
            };
            add_optional(graph, left, right, node.output.clone())?
        }
        Operation::Div => {
            let left = match t(node.inputs[0]) {
                Some(value) => Some(graph.add_node(
                    Operation::Div,
                    vec![value, p(node.inputs[1])?],
                    node.output.clone(),
                )?),
                None => None,
            };
            let right = match t(node.inputs[1]) {
                Some(value) => {
                    let numerator = graph.add_node(
                        Operation::Mul,
                        vec![p(node.inputs[0])?, value],
                        node.output.clone(),
                    )?;
                    let denominator = graph.add_node(
                        Operation::Mul,
                        vec![p(node.inputs[1])?, p(node.inputs[1])?],
                        ty(node.inputs[1])?,
                    )?;
                    let quotient = graph.add_node(
                        Operation::Div,
                        vec![numerator, denominator],
                        node.output.clone(),
                    )?;
                    Some(graph.add_node(
                        Operation::Scale { factor: crate::Scalar::f32(-1.0) },
                        vec![quotient],
                        node.output.clone(),
                    )?)
                }
                None => None,
            };
            add_optional(graph, left, right, node.output.clone())?
        }
        Operation::Scale { factor } => match t(node.inputs[0]) {
            Some(value) => Some(graph.add_node(
                Operation::Scale { factor: *factor },
                vec![value],
                node.output.clone(),
            )?),
            None => None,
        },
        Operation::Relu => match t(node.inputs[0]) {
            Some(value) => Some(graph.add_node(
                Operation::ReluGrad,
                vec![p(node.inputs[0])?, value],
                node.output.clone(),
            )?),
            None => None,
        },
        Operation::Exp => match t(node.inputs[0]) {
            Some(value) => Some(graph.add_node(
                Operation::Mul,
                vec![p(id)?, value],
                node.output.clone(),
            )?),
            None => None,
        },
        Operation::Log => match t(node.inputs[0]) {
            Some(value) => Some(graph.add_node(
                Operation::Div,
                vec![value, p(node.inputs[0])?],
                node.output.clone(),
            )?),
            None => None,
        },
        Operation::ReluGrad => match t(node.inputs[1]) {
            Some(value) => Some(graph.add_node(
                Operation::ReluGrad,
                vec![p(node.inputs[0])?, value],
                node.output.clone(),
            )?),
            None => None,
        },
        Operation::ZerosLike | Operation::OnesLike | Operation::StopGradient => None,
        Operation::Checkpoint => match t(node.inputs[0]) {
            Some(value) => Some(graph.add_node(
                Operation::Checkpoint,
                vec![value],
                node.output.clone(),
            )?),
            None => None,
        },
        Operation::Reshape { shape } => match t(node.inputs[0]) {
            Some(value) => Some(graph.add_node(
                Operation::Reshape { shape: shape.clone() },
                vec![value],
                node.output.clone(),
            )?),
            None => None,
        },
        Operation::Transpose { permutation } => match t(node.inputs[0]) {
            Some(value) => Some(graph.add_node(
                Operation::Transpose { permutation: permutation.clone() },
                vec![value],
                node.output.clone(),
            )?),
            None => None,
        },
        Operation::MatMul => {
            require_rank2(source, id, node.inputs[0], node.inputs[1])?;
            let left = match t(node.inputs[0]) {
                Some(value) => Some(graph.add_node(
                    Operation::MatMul,
                    vec![value, p(node.inputs[1])?],
                    node.output.clone(),
                )?),
                None => None,
            };
            let right = match t(node.inputs[1]) {
                Some(value) => Some(graph.add_node(
                    Operation::MatMul,
                    vec![p(node.inputs[0])?, value],
                    node.output.clone(),
                )?),
                None => None,
            };
            add_optional(graph, left, right, node.output.clone())?
        }
        operation => {
            return Err(AutodiffError::UnsupportedOperation {
                node: id,
                operation: operation.clone(),
            });
        }
    };
    Ok(result)
}

fn copy_primal(source: &Graph) -> Result<(Graph, Vec<NodeId>), AutodiffError> {
    let mut graph = Graph::new();
    let mut mapped_nodes = Vec::with_capacity(source.nodes().len());
    for node in source.nodes() {
        let inputs = node
            .inputs
            .iter()
            .map(|&id| mapped(&mapped_nodes, id))
            .collect::<Result<Vec<_>, _>>()?;
        let copied = graph.add_node(node.operation.clone(), inputs, node.output.clone())?;
        mapped_nodes.push(copied);
    }
    Ok((graph, mapped_nodes))
}

fn accumulate(
    graph: &mut Graph,
    adjoints: &mut [Option<NodeId>],
    target: NodeId,
    contribution: NodeId,
    ty: TensorType,
) -> Result<(), AutodiffError> {
    let slot = &mut adjoints[target.get() as usize];
    *slot = Some(match *slot {
        Some(existing) => graph.add_node(Operation::Add, vec![existing, contribution], ty)?,
        None => contribution,
    });
    Ok(())
}

fn add_optional(
    graph: &mut Graph,
    lhs: Option<NodeId>,
    rhs: Option<NodeId>,
    ty: TensorType,
) -> Result<Option<NodeId>, AutodiffError> {
    Ok(match (lhs, rhs) {
        (Some(lhs), Some(rhs)) => Some(graph.add_node(Operation::Add, vec![lhs, rhs], ty)?),
        (Some(value), None) | (None, Some(value)) => Some(value),
        (None, None) => None,
    })
}

fn mapped(mapping: &[NodeId], id: NodeId) -> Result<NodeId, AutodiffError> {
    mapping
        .get(id.get() as usize)
        .copied()
        .ok_or(AutodiffError::InvalidNode(id))
}

fn node_type(graph: &Graph, id: NodeId) -> Result<&TensorType, AutodiffError> {
    graph
        .nodes()
        .get(id.get() as usize)
        .map(|node| &node.output)
        .ok_or(AutodiffError::InvalidNode(id))
}

fn ensure_floating(graph: &Graph, id: NodeId) -> Result<(), AutodiffError> {
    let dtype = node_type(graph, id)?.dtype;
    if matches!(dtype, DType::F16 | DType::Bf16 | DType::F32 | DType::F64) {
        Ok(())
    } else {
        Err(AutodiffError::NonFloatingPoint { node: id, dtype })
    }
}

fn inverse_permutation(permutation: &[usize]) -> Option<Vec<usize>> {
    let mut inverse = vec![usize::MAX; permutation.len()];
    for (output_axis, &input_axis) in permutation.iter().enumerate() {
        if input_axis >= permutation.len() || inverse[input_axis] != usize::MAX {
            return None;
        }
        inverse[input_axis] = output_axis;
    }
    Some(inverse)
}

fn require_rank2(
    graph: &Graph,
    node: NodeId,
    lhs: NodeId,
    rhs: NodeId,
) -> Result<(), AutodiffError> {
    if node_type(graph, lhs)?.shape.rank() == 2 && node_type(graph, rhs)?.shape.rank() == 2 {
        Ok(())
    } else {
        Err(AutodiffError::MatMulRequiresRank2 { node })
    }
}

fn transposed_matrix_type(ty: TensorType) -> TensorType {
    debug_assert_eq!(ty.shape.rank(), 2);
    TensorType::new(
        ty.dtype,
        Shape::new(vec![ty.shape.dims()[1], ty.shape.dims()[0]]),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Scalar;

    fn vector_type() -> TensorType {
        TensorType::new(DType::F32, Shape::new(vec![4]))
    }

    #[test]
    fn reverse_mode_builds_product_rule_and_accumulates_paths() {
        let mut graph = Graph::new();
        let x = graph.add_input("x", vector_type()).unwrap();
        let square = graph
            .add_node(Operation::Mul, vec![x, x], vector_type())
            .unwrap();
        graph.set_outputs(vec![square]).unwrap();

        let transformed = grad(&graph, square, &[x]).unwrap();
        assert_eq!(transformed.gradients.len(), 1);
        assert_eq!(transformed.graph.outputs(), transformed.gradients.as_slice());
        assert!(transformed
            .graph
            .nodes()
            .iter()
            .any(|node| matches!(node.operation, Operation::OnesLike)));
        assert!(transformed
            .graph
            .nodes()
            .iter()
            .any(|node| matches!(node.operation, Operation::Add)));
    }

    #[test]
    fn stop_gradient_produces_an_explicit_zero() {
        let mut graph = Graph::new();
        let x = graph.add_input("x", vector_type()).unwrap();
        let stopped = graph
            .add_node(Operation::StopGradient, vec![x], vector_type())
            .unwrap();
        graph.set_outputs(vec![stopped]).unwrap();

        let transformed = grad(&graph, stopped, &[x]).unwrap();
        let gradient = &transformed.graph.nodes()[transformed.gradients[0].get() as usize];
        assert!(matches!(gradient.operation, Operation::ZerosLike));
    }

    #[test]
    fn jvp_adds_explicit_tangent_inputs() {
        let mut graph = Graph::new();
        let x = graph.add_input("x", vector_type()).unwrap();
        let scaled = graph
            .add_node(
                Operation::Scale {
                    factor: Scalar::f32(3.0),
                },
                vec![x],
                vector_type(),
            )
            .unwrap();
        graph.set_outputs(vec![scaled]).unwrap();

        let transformed = jvp(&graph, scaled, &[x]).unwrap();
        assert_eq!(transformed.tangent_inputs.len(), 1);
        assert_eq!(transformed.graph.outputs().len(), 2);
        assert!(matches!(
            transformed.graph.nodes()[transformed.tangent_output.get() as usize].operation,
            Operation::Scale { .. }
        ));
    }
}
