//! Venue-neutral runtime contracts.
//!
//! This module defines the normalized boundary between SciRust's deterministic
//! quantitative core and exchange-specific I/O. It deliberately contains no
//! network client and no live-order policy. Adapters translate venue-native
//! payloads into these types; deterministic runtime code consumes the normalized
//! stream.

use serde::{Deserialize, Serialize};

use crate::market::Candle;
use crate::orderbook::OrderBook;
use crate::orders::{FeeSchedule, Instrument, OrderType, Side, TimeInForce};

/// Normalized trading rules and identity for one venue instrument.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct VenueInstrument {
    pub venue: String,
    pub symbol: String,
    pub base: String,
    pub quote: String,
    pub tick_size: f32,
    pub step_size: f32,
    pub min_notional: f32,
    pub maker_bps: f32,
    pub taker_bps: f32,
}

impl VenueInstrument {
    pub fn validate(&self) -> bool {
        !self.venue.is_empty()
            && !self.symbol.is_empty()
            && !self.base.is_empty()
            && !self.quote.is_empty()
            && self.tick_size.is_finite()
            && self.tick_size > 0.0
            && self.step_size.is_finite()
            && self.step_size > 0.0
            && self.min_notional.is_finite()
            && self.min_notional >= 0.0
            && self.maker_bps.is_finite()
            && self.taker_bps.is_finite()
    }

    pub fn instrument(&self) -> Instrument {
        Instrument {
            tick_size: self.tick_size,
            step_size: self.step_size,
            min_notional: self.min_notional,
        }
    }

    pub fn fees(&self) -> FeeSchedule {
        FeeSchedule {
            maker_bps: self.maker_bps,
            taker_bps: self.taker_bps,
        }
    }
}

/// One normalized public trade.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct VenueTrade {
    pub venue: String,
    pub symbol: String,
    pub sequence: u64,
    pub ts_ms: i64,
    pub price: f32,
    pub qty: f32,
    /// Aggressor side when known.
    pub aggressor: Option<Side>,
}

/// Normalized market-data stream item.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum VenueMarketEvent {
    Book {
        venue: String,
        sequence: u64,
        book: OrderBook,
    },
    Trade(VenueTrade),
    Candle {
        venue: String,
        symbol: String,
        sequence: u64,
        candle: Candle,
    },
    Disconnected {
        venue: String,
        sequence: u64,
        ts_ms: i64,
    },
    Reconnected {
        venue: String,
        sequence: u64,
        ts_ms: i64,
    },
}

impl VenueMarketEvent {
    pub fn venue(&self) -> &str {
        match self
        {
            Self::Book { venue, .. }
            | Self::Candle { venue, .. }
            | Self::Disconnected { venue, .. }
            | Self::Reconnected { venue, .. } => venue,
            Self::Trade(trade) => &trade.venue,
        }
    }

    pub fn sequence(&self) -> u64 {
        match self
        {
            Self::Book { sequence, .. }
            | Self::Candle { sequence, .. }
            | Self::Disconnected { sequence, .. }
            | Self::Reconnected { sequence, .. } => *sequence,
            Self::Trade(trade) => trade.sequence,
        }
    }

    pub fn ts_ms(&self) -> i64 {
        match self
        {
            Self::Book { book, .. } => book.ts_ms,
            Self::Trade(trade) => trade.ts_ms,
            Self::Candle { candle, .. } => candle.ts_ms,
            Self::Disconnected { ts_ms, .. } | Self::Reconnected { ts_ms, .. } => *ts_ms,
        }
    }
}

/// A venue-neutral order request. `client_order_id` is generated by the local
/// runtime and remains stable across venue acknowledgement/replay.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct VenueOrderRequest {
    pub client_order_id: u64,
    pub symbol: String,
    pub side: Side,
    pub order_type: OrderType,
    pub qty: f32,
    pub tif: TimeInForce,
    pub reduce_only: bool,
    pub post_only: bool,
}

impl VenueOrderRequest {
    pub fn validate_against(&self, instrument: &VenueInstrument) -> bool {
        if !instrument.validate()
            || self.symbol != instrument.symbol
            || !self.qty.is_finite()
            || self.qty <= 0.0
        {
            return false;
        }
        let qty = instrument.instrument().round_qty(self.qty);
        if qty <= 0.0
        {
            return false;
        }
        match self.order_type.limit_price()
        {
            Some(price) =>
            {
                price.is_finite()
                    && price > 0.0
                    && instrument.instrument().meets_min_notional(price, qty)
            },
            None => true,
        }
    }
}

/// Runtime command sent to a venue adapter.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum VenueOrderCommand {
    Submit(VenueOrderRequest),
    Cancel {
        client_order_id: u64,
    },
    Amend {
        client_order_id: u64,
        new_qty: f32,
        new_limit_price: Option<f32>,
    },
}

/// Normalized private execution event emitted by a venue adapter.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum VenueExecutionEvent {
    Accepted {
        sequence: u64,
        ts_ms: i64,
        client_order_id: u64,
        venue_order_id: String,
    },
    Rejected {
        sequence: u64,
        ts_ms: i64,
        client_order_id: u64,
        reason: String,
    },
    Fill {
        sequence: u64,
        ts_ms: i64,
        client_order_id: u64,
        price: f32,
        qty: f32,
        fee: f32,
        taker: bool,
    },
    Canceled {
        sequence: u64,
        ts_ms: i64,
        client_order_id: u64,
    },
    Amended {
        sequence: u64,
        ts_ms: i64,
        client_order_id: u64,
        new_qty: f32,
        new_limit_price: Option<f32>,
    },
    Disconnected {
        sequence: u64,
        ts_ms: i64,
    },
    Reconnected {
        sequence: u64,
        ts_ms: i64,
    },
}

impl VenueExecutionEvent {
    pub fn sequence(&self) -> u64 {
        match self
        {
            Self::Accepted { sequence, .. }
            | Self::Rejected { sequence, .. }
            | Self::Fill { sequence, .. }
            | Self::Canceled { sequence, .. }
            | Self::Amended { sequence, .. }
            | Self::Disconnected { sequence, .. }
            | Self::Reconnected { sequence, .. } => *sequence,
        }
    }

    pub fn ts_ms(&self) -> i64 {
        match self
        {
            Self::Accepted { ts_ms, .. }
            | Self::Rejected { ts_ms, .. }
            | Self::Fill { ts_ms, .. }
            | Self::Canceled { ts_ms, .. }
            | Self::Amended { ts_ms, .. }
            | Self::Disconnected { ts_ms, .. }
            | Self::Reconnected { ts_ms, .. } => *ts_ms,
        }
    }

    pub fn client_order_id(&self) -> Option<u64> {
        match self
        {
            Self::Accepted {
                client_order_id, ..
            }
            | Self::Rejected {
                client_order_id, ..
            }
            | Self::Fill {
                client_order_id, ..
            }
            | Self::Canceled {
                client_order_id, ..
            }
            | Self::Amended {
                client_order_id, ..
            } => Some(*client_order_id),
            Self::Disconnected { .. } | Self::Reconnected { .. } => None,
        }
    }
}

/// Read-side contract implemented by exchange-specific market-data adapters.
pub trait VenueMarketDataAdapter {
    fn venue(&self) -> &str;
    fn instrument(&self, symbol: &str) -> Option<VenueInstrument>;
    fn poll_event(&mut self) -> Option<VenueMarketEvent>;
}

/// Private execution contract. Implementations may be paper, replay, or live;
/// live authorization remains outside this trait.
pub trait VenueExecutionAdapter {
    type Error;

    fn venue(&self) -> &str;
    fn send(&mut self, command: &VenueOrderCommand) -> Result<(), Self::Error>;
    fn poll_event(&mut self) -> Option<VenueExecutionEvent>;
}

#[cfg(test)]
mod tests {
    use super::*;

    fn instrument() -> VenueInstrument {
        VenueInstrument {
            venue: "x".to_string(),
            symbol: "BTC-USDT".to_string(),
            base: "BTC".to_string(),
            quote: "USDT".to_string(),
            tick_size: 0.1,
            step_size: 0.001,
            min_notional: 10.0,
            maker_bps: 1.0,
            taker_bps: 5.0,
        }
    }

    #[test]
    fn normalized_instrument_maps_to_existing_rules() {
        let v = instrument();
        assert!(v.validate());
        let i = v.instrument();
        assert!((i.tick_size - 0.1).abs() < 1e-6);
        assert!((v.fees().taker_bps - 5.0).abs() < 1e-6);
    }

    #[test]
    fn request_validation_reuses_instrument_contract() {
        let req = VenueOrderRequest {
            client_order_id: 7,
            symbol: "BTC-USDT".to_string(),
            side: Side::Buy,
            order_type: OrderType::Limit { price: 100.0 },
            qty: 0.2,
            tif: TimeInForce::Gtc,
            reduce_only: false,
            post_only: true,
        };
        assert!(req.validate_against(&instrument()));

        let mut too_small = req.clone();
        too_small.qty = 0.01;
        assert!(!too_small.validate_against(&instrument()));
    }

    #[test]
    fn execution_event_accessors_are_total() {
        let event = VenueExecutionEvent::Fill {
            sequence: 11,
            ts_ms: 1234,
            client_order_id: 9,
            price: 100.0,
            qty: 1.0,
            fee: 0.1,
            taker: true,
        };
        assert_eq!(event.sequence(), 11);
        assert_eq!(event.ts_ms(), 1234);
        assert_eq!(event.client_order_id(), Some(9));
    }
}
