//! Validation of the training-envelope port against reference oracle values.
//!
//! The fixtures in `support/envelope_oracle.rs` were generated by running the
//! ORIGINAL Python functions of the ITD research simulator
//! (`itd_research.ood_shift.detector` / `.policy`, standardization from
//! `itd_research.ood.reference.fit_reference`) on a seeded calibration matrix —
//! see `support/gen_envelope_oracle.py`. Integer outputs (attributions, gate
//! states) must match exactly; floating-point outputs are held to a tight
//! relative tolerance.

#[allow(dead_code)]
mod envelope_oracle {
    include!("support/envelope_oracle.rs");
}

use envelope_oracle as od;
use scirust_multivariate::{
    GateState, TrainingEnvelope, confidence_discount, monotone_separation, three_state_gate,
};

const REL: f64 = 1e-12;
const ABS: f64 = 1e-14;

fn is_close(a: f64, b: f64) -> bool {
    (a - b).abs() <= ABS + REL * a.abs().max(b.abs())
}

#[track_caller]
fn assert_close(a: f64, b: f64, ctx: &str) {
    assert!(
        is_close(a, b),
        "{ctx}: got {a:.17e}, want {b:.17e}, diff {:.3e}",
        (a - b).abs()
    );
}

fn calibration_rows() -> Vec<Vec<f64>> {
    od::CALIBRATION
        .chunks(od::N_FEATURES)
        .map(|row| row.to_vec())
        .collect()
}

fn state_code(state: GateState) -> usize {
    match state
    {
        GateState::Accept => 0,
        GateState::ReducedConfidence => 1,
        GateState::Abstain => 2,
    }
}

#[test]
fn fitted_statistics_match_the_reference() {
    let envelope =
        TrainingEnvelope::fit(&calibration_rows(), od::SEVERITY_K).expect("valid calibration");
    assert_eq!(envelope.dimension(), od::N_FEATURES);
    for (axis, (&got, &want)) in envelope.mean().iter().zip(od::FITTED_MEAN).enumerate()
    {
        assert_close(got, want, &format!("mean axis {axis}"));
    }
    for (axis, (&got, &want)) in envelope.scale().iter().zip(od::FITTED_SCALE).enumerate()
    {
        assert_close(got, want, &format!("scale axis {axis}"));
    }
    // The constant calibration axis must have received the floor substitution.
    assert_eq!(envelope.scale()[od::N_FEATURES - 1], 1.0);
}

#[test]
fn probe_deviations_severities_and_attributions_match_the_reference() {
    let envelope =
        TrainingEnvelope::fit(&calibration_rows(), od::SEVERITY_K).expect("valid calibration");
    for (probe_index, probe) in od::PROBES.chunks(od::N_FEATURES).enumerate()
    {
        let deviations = envelope.per_axis_deviation(probe).expect("valid probe");
        let expected =
            &od::PROBE_DEVIATIONS[probe_index * od::N_FEATURES..(probe_index + 1) * od::N_FEATURES];
        for (axis, (&got, &want)) in deviations.iter().zip(expected).enumerate()
        {
            assert_close(got, want, &format!("probe {probe_index} deviation {axis}"));
        }
        let severity = envelope.severity(probe).expect("valid probe");
        assert_close(
            severity,
            od::PROBE_SEVERITIES[probe_index],
            &format!("probe {probe_index} severity"),
        );
        let attribution = envelope.attribution(probe).expect("valid probe");
        assert_eq!(
            attribution,
            od::PROBE_ATTRIBUTIONS[probe_index],
            "probe {probe_index} attribution"
        );
    }
}

#[test]
fn three_state_sweep_matches_the_reference() {
    for (index, &severity) in od::SWEEP.iter().enumerate()
    {
        let discount = confidence_discount(severity, od::S_LOW, od::S_HIGH).expect("finite inputs");
        assert_close(
            discount,
            od::SWEEP_DISCOUNTS[index],
            &format!("discount {index}"),
        );
        let decision = three_state_gate(severity, od::S_LOW, od::S_HIGH).expect("finite inputs");
        assert_eq!(
            state_code(decision.state),
            od::SWEEP_STATES[index],
            "state {index}"
        );
        assert_close(
            decision.confidence,
            od::SWEEP_CONFIDENCES[index],
            &format!("confidence {index}"),
        );
    }
}

#[test]
fn degenerate_band_matches_the_reference_step() {
    for (index, &severity) in od::SWEEP.iter().enumerate()
    {
        let decision = three_state_gate(severity, 2.0, 2.0).expect("finite inputs");
        assert_eq!(
            state_code(decision.state),
            od::DEGENERATE_STATES[index],
            "degenerate state {index}"
        );
        assert_close(
            decision.confidence,
            od::DEGENERATE_CONFIDENCES[index],
            &format!("degenerate confidence {index}"),
        );
    }
}

#[test]
fn monotone_separation_matches_the_reference() {
    let got = monotone_separation(od::SEP_SCORES, od::SEP_LEVELS)
        .expect("valid input")
        .expect("cross-level pairs exist");
    assert_close(got, od::SEPARATION, "separation");
}
