//! End-to-end deterministic VQNet-like training on the native SciRust stack.
//!
//! The synthetic target is generated by a one-qubit `Ry(x + theta*)` model with
//! known `theta*`. Training starts from a different angle and learns through:
//!
//! `DataLoader -> QuantumModule -> ComputationalBasisReadout -> MseLoss`
//!
//! using `TrainingSession<Sgd>`. No Python runtime, FFI, secondary simulator,
//! custom optimizer, or VQNet-specific data loader is involved.

use scirust_core::autodiff::optim::Sgd;
use scirust_core::autodiff::reverse::{Tape, Tensor};
use scirust_core::data::{DataLoader, InMemoryDataset};
use scirust_core::nn::loss::MseLoss;
use scirust_core::nn::module::Module;
use scirust_core::nn::sequential::Sequential;
use scirust_core::vqnet::{
    ComputationalBasisReadout, EntanglementTopology, EntanglingGate, ParameterInitializer,
    QuantumModule, RotationAxis, TrainingSession, VariationalCircuitBuilder,
};

const TARGET_THETA: f32 = 0.65;

fn target_probabilities(feature: f32) -> [f32; 2] {
    let z = (feature + TARGET_THETA).cos();
    [0.5 * (1.0 + z), 0.5 * (1.0 - z)]
}

fn main() {
    let features = vec![-0.9f32, -0.3, 0.25, 0.8];
    let mut targets = Vec::with_capacity(features.len() * 2);
    for &feature in &features {
        targets.extend_from_slice(&target_probabilities(feature));
    }

    let dataset = InMemoryDataset::new(features.clone(), targets, 1, 2);
    let mut loader = DataLoader::new(dataset, 2, true, 0x51a7);

    let mut builder = VariationalCircuitBuilder::new(1).expect("valid one-qubit circuit");
    builder
        .angle_encoding(RotationAxis::Y, &[0])
        .expect("valid angle encoding");
    builder
        .variational_ansatz(
            1,
            &[RotationAxis::Y],
            EntanglementTopology::None,
            EntanglingGate::Cnot,
        )
        .expect("valid one-parameter ansatz");
    builder
        .measure_computational_basis_moments()
        .expect("canonical probability moments");
    let circuit = builder.build().expect("complete measured circuit");

    let probabilities =
        ComputationalBasisReadout::from_circuit(&circuit).expect("matching probability readout");
    let quantum = QuantumModule::new(circuit, ParameterInitializer::Constant(0.05))
        .expect("finite quantum initializer");
    let mut model = Sequential::new().add(quantum).add(probabilities);

    let loss = MseLoss::new();
    let mut session = TrainingSession::new(Sgd::new(0.2));
    let mut final_mean_loss = f32::NAN;

    for epoch in 0..40u64 {
        let report = session
            .train_loader_epoch(&mut model, &loss, &mut loader, epoch)
            .expect("deterministic training epoch");
        final_mean_loss = report.mean_loss();
        if epoch % 10 == 0 || epoch == 39 {
            println!("epoch={epoch:02} mean_loss={:.8}", report.mean_loss());
        }
    }

    let state = model.state_dict();
    let learned_theta = state
        .get("0.parameters")
        .expect("quantum parameters in Sequential state")
        .data[0];

    let tape = Tape::new();
    let input = tape.input(Tensor::from_vec(features.clone(), features.len(), 1));
    let prediction = model.forward(&tape, input);
    let prediction = tape.value(prediction.idx());

    println!("target_theta={TARGET_THETA:.6}");
    println!("learned_theta={learned_theta:.6}");
    println!("final_mean_loss={final_mean_loss:.8}");
    for (sample, (&feature, probabilities)) in features
        .iter()
        .zip(prediction.data.chunks_exact(2))
        .enumerate()
    {
        let target = target_probabilities(feature);
        println!(
            "sample={sample} x={feature:+.3} pred=[{:.6}, {:.6}] target=[{:.6}, {:.6}]",
            probabilities[0], probabilities[1], target[0], target[1]
        );
    }
}
