//! Validation of the 3-D region/topology port against reference oracle values.
//!
//! The fixtures in `support/region3_oracle.rs` were generated by running the
//! ORIGINAL Python functions of the ITD research simulator
//! (`itd_research.mission8.vortex_regions`) on fixed literal fields — see
//! `support/gen_region3_oracle.py`. Integer outputs (labels, sizes, counts,
//! events) must match exactly; floating-point outputs (centroids, overlap
//! metrics) are held to the same tight tolerance as `tests/oracle.rs`.

#[allow(dead_code)]
mod region3_oracle {
    include!("support/region3_oracle.rs");
}

use region3_oracle as od;
use scirust_itd::{
    Comparison, Field3, Mask3, TopologyEvent, TopologyEventKind, core_count_series, detect_regions,
    detect_topology_events, dice, iou, label_components, max_nearest_distance, threshold_mask,
};

const REL: f64 = 1e-9;
const ABS: f64 = 1e-11;

fn is_close(a: f64, b: f64) -> bool {
    (a - b).abs() <= ABS + REL * a.abs().max(b.abs())
}

#[track_caller]
fn assert_close(a: f64, b: f64, ctx: &str) {
    assert!(
        is_close(a, b),
        "{ctx}: got {a:.17e}, want {b:.17e}, diff {:.3e}",
        (a - b).abs()
    );
}

fn field(data: &[f64]) -> Field3 {
    Field3::from_vec(od::NZ, od::NY, od::NX, data.to_vec()).expect("oracle field is well-formed")
}

fn kind_code(kind: TopologyEventKind) -> usize {
    match kind
    {
        TopologyEventKind::CoreMerger => 0,
        TopologyEventKind::CoreSplit => 1,
    }
}

#[track_caller]
fn assert_events(got: &[TopologyEvent], want: &[(usize, usize, usize, usize)], ctx: &str) {
    assert_eq!(got.len(), want.len(), "{ctx}: event count");
    for (event, expected) in got.iter().zip(want)
    {
        assert_eq!(
            (
                kind_code(event.kind),
                event.frame_index,
                event.from_count,
                event.to_count,
            ),
            *expected,
            "{ctx}: event mismatch"
        );
    }
}

#[test]
fn two_blob_labelling_matches_the_reference_exactly() {
    let (labeling, records) = detect_regions(
        &field(od::FIELD_TWO_BLOBS),
        od::THRESHOLD,
        Comparison::Greater,
        od::MIN_CELLS,
        false,
    )
    .expect("finite oracle field");
    assert_eq!(labeling.labels(), od::LABELS_TWO_BLOBS, "dense label field");
    assert_eq!(records.len(), od::RECORDS_TWO_BLOBS.len(), "record count");
    for (record, &(label, volume, cz, cy, cx)) in records.iter().zip(od::RECORDS_TWO_BLOBS)
    {
        assert_eq!(record.label, label, "record label");
        assert_eq!(record.volume_cells, volume, "record volume");
        assert_close(record.centroid[0], cz, "centroid z");
        assert_close(record.centroid[1], cy, "centroid y");
        assert_close(record.centroid[2], cx, "centroid x");
    }
}

#[test]
fn periodic_seam_matches_the_reference_component_structure() {
    let mask = threshold_mask(&field(od::FIELD_SEAM), od::THRESHOLD, Comparison::Greater)
        .expect("finite oracle field");
    let bounded = label_components(&mask, false);
    let periodic = label_components(&mask, true);
    assert_eq!(bounded.sizes(), od::SEAM_BOUNDED_SIZES, "bounded sizes");
    assert_eq!(periodic.sizes(), od::SEAM_PERIODIC_SIZES, "periodic sizes");
}

#[test]
fn overlap_metrics_match_the_reference() {
    let mask_a = threshold_mask(
        &field(od::FIELD_TWO_BLOBS),
        od::THRESHOLD,
        Comparison::Greater,
    )
    .expect("finite oracle field");
    let mask_b = threshold_mask(
        &field(od::FIELD_TWO_BLOBS_ROLLED_X),
        od::THRESHOLD,
        Comparison::Greater,
    )
    .expect("finite oracle field");
    let got_iou = iou(&mask_a, &mask_b)
        .expect("same shape")
        .expect("non-empty union");
    let got_dice = dice(&mask_a, &mask_b)
        .expect("same shape")
        .expect("non-empty masks");
    let got_mnd = max_nearest_distance(&mask_a, &mask_b)
        .expect("same shape")
        .expect("non-empty masks");
    assert_close(got_iou, od::IOU_A_B, "IoU");
    assert_close(got_dice, od::DICE_A_B, "Dice");
    assert_close(got_mnd, od::MAX_NEAREST_A_B, "max nearest distance");
}

#[test]
fn merger_sequence_counts_and_events_match_the_reference() {
    let frames = [
        od::FRAME_0,
        od::FRAME_1,
        od::FRAME_2,
        od::FRAME_3,
        od::FRAME_4,
    ]
    .iter()
    .map(|data| field(data))
    .collect::<Vec<_>>();
    let counts = core_count_series(
        &frames,
        od::THRESHOLD,
        Comparison::Greater,
        od::MIN_CELLS,
        false,
    )
    .expect("finite oracle frames");
    assert_eq!(counts, od::COUNTS_SEQUENCE, "component-count series");
    let events = detect_topology_events(&counts, 2);
    assert_events(&events, od::EVENTS_SEQUENCE, "sequence events");
}

#[test]
fn persistence_regression_cases_match_the_reference() {
    assert_events(
        &detect_topology_events(od::COUNTS_BLIP, 2),
        od::EVENTS_BLIP,
        "transient blip",
    );
    assert_events(
        &detect_topology_events(od::COUNTS_SUSTAINED, 2),
        od::EVENTS_SUSTAINED,
        "sustained change",
    );
}

#[test]
fn mask_shape_roundtrip_matches_the_oracle_dims() {
    let mask = Mask3::from_vec(
        od::NZ,
        od::NY,
        od::NX,
        vec![false; od::NZ * od::NY * od::NX],
    )
    .expect("valid dims");
    assert_eq!(mask.shape(), (od::NZ, od::NY, od::NX));
}
